---
version: '3.8'
services:
  app:
    build:
      context: '.'
      target: 'base'
    command: sh -c 'npm i && npm run start:dev'
    environment:
      - APP_PORT=3000
      - APP_DEBUG=false
      - DB_TYPE=mysql
      - DB_NAME=onedb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - '3000:3000'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app:cached
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE
