---
version: '3.8'
services:
  app:
    build:
      context: '.'
      target: 'base'
    command: sh -c 'npm i && npm run start:dev'
    ports:
      - '3000:3000'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app:cached
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
